<template>
  <div class="feature-services">
    <div
      class="
        container
        bg-featured-services bg-cover bg-fixed
        mx-auto
        px-5
        sm:px-10
        xl:px-20
        3xl:px-28
        py-8
        sm:py-12
        lg:py-20
        3xl:py-24
        sm:rounded-md
        lg:rounded-lg
      "
    >
      <div class="flex justify-center md:justify-start">
        <h2
          class="
            text-six
            md:text-five
            lg:text-four
            xl:text-three
            2xl:text-two
            font-bold
            text-white
            pb-8
            sm:pb-12
            lg:pb-20
            3xl:pb-24
          "
        >
          Featured Services
        </h2>
      </div>
      <div
        class="
          flex flex-col
          md:flex-row
          items-stretch
          justify-between
          space-x-0
          md:space-x-5
          lg:space-x-10
        "
      >
        <div
          class="
            bg-white
            shadow-lg
            rounded-md
            px-4
            py-6
            md:pb-20
            lg:pb-24 lg:pt-9 lg:px-9
            text-center
            md:text-left
            w-full
            relative
            featured-column
          "
        >
          <div
            class="
              fs-img-wrap
              rounded-full
              flex
              align-center
              flex-wrap
              mx-auto
              md:ml-0
            "
          >
            <img
              src="../../assets/images/emergency-services.svg"
              alt=""
              class="
                mx-auto
                h-100
                transition-transform
                duration-500
                ease-in-out
              "
            />
          </div>
          <h3
            class="
              text-lg
              xl:text-xl
              3xl:text-2xl
              font-semibold
              mt-5
              lg:mt-10
              mb-2
              lg:mb-6
              fs-title
              transition
              duration-500
              ease-in-out
              cursor-pointer
            "
          >
            <a href=""> Apply with your home</a>
          </h3>
          <p class="text-sm sm:text-base lg:text-lg mt-2">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          </p>
          <a
            href="#"
            class="
              fs-arrow
              flex
              items-center
              justify-center
              bg-gray
              rounded-full
              md:absolute
              mx-auto
              md:ml-0
              mt-5
              md:mt-0
              cursor-pointer
              duration-500
              ease-in-out
              transition
            "
          >
            <svg
              width="25"
              height="25"
              viewBox="0 0 25 25"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M21.6699 12.5022L3.49856 12.5022M14.6033 5.43555L21.6699 12.5022L14.6033 5.43555ZM21.6699 12.5022L14.6033 19.5688L21.6699 12.5022Z"
                stroke="#313131"
                stroke-width="1.5"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
            </svg>
          </a>
        </div>

        <div
          class="
            bg-white
            shadow-lg
            rounded-md
            px-4
            py-6
            md:pb-20
            lg:pb-24 lg:pt-9 lg:px-9
            mt-4
            md:mt-0
            text-center
            md:text-left
            w-full
            relative
            featured-column
          "
        >
          <div
            class="
              fs-img-wrap
              rounded-full
              flex
              align-center
              flex-wrap
              mx-auto
              md:ml-0
            "
          >
            <img
              src="../../assets/images/long-term-project.svg"
              alt=""
              class="
                mx-auto
                h-100
                transition-transform
                duration-500
                ease-in-out
              "
            />
          </div>
          <h3
            class="
              text-lg
              xl:text-xl
              3xl:text-2xl
              font-semibold
              mt-5
              lg:mt-10
              mb-2
              lg:mb-6
              fs-title
              transition
              duration-500
              ease-in-out
              cursor-pointer
            "
          >
            <a href=""> Complete the form</a>
          </h3>
          <p class="text-sm sm:text-base lg:text-lg mt-2">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          </p>
          <a
            href="#"
            class="
              fs-arrow
              flex
              items-center
              justify-center
              bg-gray
              rounded-full
              md:absolute
              mx-auto
              md:ml-0
              mt-5
              md:mt-0
              cursor-pointer
              duration-500
              ease-in-out
              transition
            "
          >
            <svg
              width="25"
              height="25"
              viewBox="0 0 25 25"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M21.6699 12.5022L3.49856 12.5022M14.6033 5.43555L21.6699 12.5022L14.6033 5.43555ZM21.6699 12.5022L14.6033 19.5688L21.6699 12.5022Z"
                stroke="#313131"
                stroke-width="1.5"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
            </svg>
          </a>
        </div>

        <div
          class="
            bg-white
            shadow-lg
            rounded-md
            px-4
            py-6
            md:pb-20
            lg:pb-24 lg:pt-9 lg:px-9
            mt-4
            md:mt-0
            text-center
            md:text-left
            w-full
            relative
            featured-column
          "
        >
          <div
            class="
              fs-img-wrap
              rounded-full
              flex
              align-center
              flex-wrap
              mx-auto
              md:ml-0
            "
          >
            <img
              src="../../assets/images/small-business.svg"
              alt=""
              class="
                mx-auto
                h-100
                transition-transform
                duration-500
                ease-in-out
              "
            />
          </div>
          <h3
            class="
              text-lg
              xl:text-xl
              3xl:text-2xl
              font-semibold
              mt-5
              lg:mt-10
              mb-2
              lg:mb-6
              fs-title
              transition
              duration-500
              ease-in-out
              cursor-pointer
            "
          >
            <a href=""> Choose the fair rate</a>
          </h3>
          <p class="text-sm sm:text-base lg:text-lg mt-2">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          </p>
          <a
            href="#"
            class="
              fs-arrow
              flex
              items-center
              justify-center
              bg-gray
              rounded-full
              md:absolute
              mx-auto
              md:ml-0
              mt-5
              md:mt-0
              cursor-pointer
              duration-500
              ease-in-out
              transition
            "
          >
            <svg
              width="25"
              height="25"
              viewBox="0 0 25 25"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M21.6699 12.5022L3.49856 12.5022M14.6033 5.43555L21.6699 12.5022L14.6033 5.43555ZM21.6699 12.5022L14.6033 19.5688L21.6699 12.5022Z"
                stroke="#313131"
                stroke-width="1.5"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
            </svg>
          </a>
        </div>
      </div>
      <div class="flex justify-center md:justify-end mt-8">
        <button
          class="
            p-3
            xl:px-10 xl:p-5
            font-semibold
            text-md
            2xl:text-lg
            bg-primary
            text-white
            rounded-sm
            shadow-3xl
            uppercase
            hover:bg-green
            duration-500
            ease-in-out
          "
        >
          see all
        </button>
      </div>
    </div>
  </div>
</template>
